project:
  type: website
  output-dir: docs
website:
  title: "Security Research Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rock3traccoon
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cyborg
    css: styles.css



